# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20181115_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='val',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([]),
        ),
    ]
